apiVersion: v2
name: datahub-executor-worker
description: A Helm chart for datahub-executor-worker
type: application
version: 0.0.10
appVersion: 0.0.1
maintainers:
  - name: DataHub
    email: datahub@acryl.io
